version: '1'

networks: 
  forze_armate_net: 

services:
  db: mysql:8.0
  container_name: db_forze_armate
  environment:
      MYSQL_ROOT_PASSWORD: DataBase1203!
      MYSQL_DATABASE: forze_armate
      MYSQL_USER: root
      MYSQL_PASSWORD: DataBasse1203!
      MYSQL_TCP_PORT: 6033
    ports: 
      - 6033:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
    - forze_armate_net
    healthcheck:
          test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
          start_period: 5s
          interval: 5s
          timeout: 5s
          retries: 20

volumes: 
  dbdata: 
    driver: local