# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: ForzeArmate

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: 
    contents: read 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file ./SitoForzeArmate/pom.xml

    - name: Docker login 
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker build and push forze armate
      uses: docker/build-push-action@v5
      with: 
        context: .
        file: ./Dockerfile
        push: true 
        tags: stefanochiogna/forze_armate:latest
      
    - name: Docker build and push database
      uses: docker/build-push-action@v5
      with: 
        context: . 
        file: ./DockerfileSQL
        push: true
        tags: stefanochiogna/db:latest
      
